### ISSUE TITLE
Firestore]: Listen for Query(target=Query(users where orientation!=women and ****==false order by orientation, __name__);limitType=LIMIT_TO_FIRST) failed: Status{code=FAILED_PRECONDITION, description=The query requires an index. You can create it here: 

### ISSUE THREAD

**Issue by testerraspi** [alejandro-piguave/TinderCloneCompose#4]
Hey thanks for the fix from the last one 

i dont no 

i have a new one 

can please help me 

thanks

**Comment by testerraspi** [comment]
thanks i found the problem

**Comment by testerraspi** [comment]
no the problem is not fixed

**Comment by alejandro-piguave** [comment]
<img width="1064" alt="Screenshot 2024-04-28 at 16 08 39" src="https://github.com/alejandro-piguave/TinderCloneCompose/assets/45740598/89bbe21f-2caa-40c2-9490-5a9de9dcc128">
You have to create an index in the Firebase console of your project with these fields. I hope that helps.
