### ISSUE TITLE
Picture dont show

### ISSUE THREAD

**Issue by testerraspi** [alejandro-piguave/TinderCloneCompose#6]
I have fixed the last error because i see not oitcure in homescreen or in Messages

**Comment by alejandro-piguave** [comment]
<img width="1024" alt="Screenshot 2024-05-07 at 01 04 44" src="https://github.com/alejandro-piguave/TinderCloneCompose/assets/45740598/ab528d69-ee93-4645-8052-e74b5c27c437">
I forgot to mention it but as the project is now, you have to set your storage rules like this in order for pictures to work. I will be reverting this in incoming commits though.

**Comment by testerraspi** [comment]
Thanks for the fast answer because the Error With the picture Not bei fixed. I wait when you change the things. Thanks you very much

**Comment by alejandro-piguave** [comment]
I realized what the problem is in the current commit. Inside of "PictureApi", the property "PROJECT_ID", it's value should be changed to your project's bucket. This should fix the problem while I work on the next commit.

**Comment by alejandro-piguave** [comment]
With the recent commits, it should work. Let me know if it keeps happening.

**Comment by testerraspi** [comment]
Hello thanks for the Changes. because the Picture are see in the Homescreen , because in the Messages write objekt does not exist

**Comment by testerraspi** [comment]
hello yes i see the Picture because in messages i see see loading picture and then Objekt does not exist at loacation

**Comment by alejandro-piguave** [comment]
does the picture exist in your Firebase storage bucket?

**Comment by testerraspi** [comment]
No notfing exist

Alejandro Piguave ***@***.***> schrieb am Di., 7. Mai 2024,
19:34:

**Comment by testerraspi** [comment]
![Unbenannt](https://github.com/alejandro-piguave/TinderCloneCompose/assets/48212471/51323687-bcd1-4e2f-87e1-59a4285b0c76)
![Unbenannt1](https://github.com/alejandro-piguave/TinderCloneCompose/assets/48212471/3c192e47-b052-4500-a015-cd6c904a04f6)

**Comment by testerraspi** [comment]
when i make a new account , i see the Users folder in the Storage of Firebase then i have a match and then the folder users clear automatic , sry for my bad englisch

**Comment by alejandro-piguave** [comment]
I think I know what the mistake was and I've just updated the project fixing it. Can you try again with new users?

**Comment by testerraspi** [comment]
Moment i testet it

**Comment by testerraspi** [comment]
Yes works perfekt , You make with this app very good work thanks for the help

**Comment by testerraspi** [comment]
now the users Folder delete automatic in 2 minutes after createt the account

**Comment by alejandro-piguave** [comment]
Fixed.
