### ISSUE TITLE
i dont know what the Error

### ISSUE THREAD

**Issue by testerraspi** [alejandro-piguave/TinderCloneCompose#8]
I update the changes because the folder users created automatic and  10 seconds later delete hmm

**Comment by alejandro-piguave** [comment]
Hmmm, I am not sure how you are getting this since there is no method in the project that deletes users. Could you provide more information?

**Comment by testerraspi** [comment]
When i create a account , i can upload the picture the folder in firebase succesfull create , because when you login the folder automatic Delete

**Comment by alejandro-piguave** [comment]
Fixed it in last commit! Can you test it to confirm it works now?

**Comment by testerraspi** [comment]
Good moring from Austria , Yes the last changes fixed the Problem 

Thank you very much
